
VERSION_MAJOR := 0
VERSION_MINOR := 1
VERSION_PATCH := 0

VERSION := $(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH)

FINAL_FLAGS += -DVERSION_MAJOR=$(VERSION_MAJOR)
FINAL_FLAGS += -DVERSION_MINOR=$(VERSION_MINOR)
FINAL_FLAGS += -DVERSION_PATCH=$(VERSION_PATCH)
FINAL_FLAGS += -DVERSION=$(VERSION)

PREFIX ?= /usr
